import { useMemo } from "react";

export const columns = [
  {
    Header: "Name",
    accessor: "show.name",
  },
  {
    Header: "Type",
    accessor: "show.type",
  },

  {
    Header: "Language",
    accessor: "show.language",
  },
  {
    Header: "Genre(s)",
    accessor: "show.genres",
  },
  {
    Header: "Runtime",
    accessor: "show.runtime",
  },
  {
    Header: "Status",
    accessor: "show.status",
  },
];

export const data: any[] = [
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },

  {
    score: 17.592657,
    show: {
      id: 44813,
      url: "http://www.tvmaze.com/shows/44813/the-snow-spider",
      name: "The Snow Spider",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Fantasy"],
      status: "In Development",
      runtime: 30,
      premiered: null,
      officialSite: null,
    },
  },
  
];
